import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: false,
      link: {type: 'doc', id: 'getting-started/overview'},
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: '教程与工作流',
      collapsed: false,
      link: {type: 'generated-index', slug: '/tutorials'},
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
    {
      type: 'category',
      label: '界面与控件',
      collapsed: false,
      link: {type: 'generated-index', slug: '/reference'},
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: '基础知识',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'knowledge/filament-selection/filament-selection',
      },
      items: [{type: 'autogenerated', dirName: 'knowledge'}],
    },
    {
      type: 'category',
      label: '项目信息',
      collapsed: true,
      link: {type: 'doc', id: 'project/faq'},
      items: [
        'project/development-updates/development-updates',
        'project/faq',
        'project/about/about',
        'project/sponsors/sponsors',
        'project/content-license',
        {type: 'ref', id: 'project/wiki-feedback/wiki-feedback'},
      ],
    },
    {
      type: 'category',
      label: '旧版资料',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'legacy/lumina-studio-1x-guide/lumina-studio-1x-guide',
      },
      items: [{type: 'autogenerated', dirName: 'legacy'}],
    },
  ],
  releasesSidebar: [
    {
      type: 'category',
      label: '版本进展',
      collapsed: false,
      link: {type: 'doc', id: 'releases/overview'},
      items: [{type: 'autogenerated', dirName: 'releases'}],
    },
  ],
  feedbackSidebar: ['project/wiki-feedback/wiki-feedback'],
};

export default sidebars;
